// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/afthaab/urlshortner/pkg/api"
	"github.com/afthaab/urlshortner/pkg/api/handler"
	"github.com/afthaab/urlshortner/pkg/repository/interface"
	"github.com/afthaab/urlshortner/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(repoInterface interfaces.UrlRepository) (*api.ServerHTTP, error) {
	urlUseCase := usecase.NewUrlUseCase(repoInterface)
	urlHandler := handler.NewUrlHandler(urlUseCase)
	serverHTTP := api.NewServerHTTP(urlHandler)
	return serverHTTP, nil
}
